version: '3.4'

services:
  app:
    build:
      context: .
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - redis
  worker:
    build:
      context: .
    command: 'rq worker -c settings --with-scheduler default' 
    volumes:
      - ./:/app/
    env_file: .env
    depends_on:
      - redis
      - app
  scheduler:
    build:
      context: .
    command: 'rqscheduler --host "$REDIS_HOST" --port "$REDIS_PORT" -i 5'
    volumes:
      - ./:/app/
    env_file: .env
    depends_on:
      - redis
      - app
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
