# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

jobs:
  test:
    docker:
      - image: circleci/python:3.7
  steps:
    - checkout
    - run: |
        pip install -r dev-requirements.txt
        pip install .
        pytest tests --junit-xml test_output/junit.xml
    - store_test_results:
        path: test_output

  lint:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: |
          pip install black
          black --check --line-length 80 vaccine_finder tests
      - run: |
          pip install flake8
          flake8 --ignore=E501,W503,E203 vaccine_finder
          flake8 --ignore=E501,W503,E203 tests


workflows:
  version: 2
  build:
    jobs:
      - tests
      - lint
